title: Mon Site de Documentation
description: Documentation pour mon projet
baseurl: "/documentation"
url: "https://votre-nom-utilisateur.github.io"
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Navigation
navigation:
  - name: "Home"
    link: "/"
  - name: "Introduction"
    link: "/introduction"
  - name: "Installation"
    link: "/installation"
  - name: "Usage"
    link: "/usage"
  - name: "API"
    link: "/api"
  - name: "FAQ"
    link: "/faq"
